[package]
name = "ann-lib"
version = "0.1.0"
authors = ["GuXianyu <guxianyu@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_distr = "0.2.2"
rand = "*"